--- 
- name: "Launching EC2 with Apache" 
  hosts: localhost 
  gather_facts: false 
  tasks: 

    - name: "Launch instance" 
      ec2: 
       key_name: awskey                   
       group: EC2-SEC                      
       instance_type: t2.micro 
       image: ami-00c03f7f7f2ec15c3 
       wait: true                         
       assign_public_ip: yes 
       region: us-east-2 
       vpc_subnet_id: subnet-3f9d5072 
       instance_tags: 
        Name: server1 
       count_tag: Name 
       exact_count: 1 
      register: ec2 

    - debug: 
       var: item.private_ip                  
      with_items: "{{ ec2.instances }}" 

    - name: "Add the newly created host for further connections" 
      add_host: 
       name: "{{ item.private_ip }}" 
       groups: web_server 
       ansible_user: "ec2-user"
       ansible_ssh_private_key_file: /home/ec2-user/awskey.pem 
       ansible_ssh_common_args: "-o StrictHostKeyChecking=no" 
      with_items: "{{ ec2.instances }}" 

    - name: "Wait for SSH to come up"
      wait_for: 
       host: "{{ item.private_ip }}" 
       port: 22 
       state: started 
      with_items: "{{ ec2.instances }}" 

    - name: "Install Apache" 
      delegate_to: "{{ item.private_ip }}" 
      delegate_facts: true  
      with_items: "{{ ec2.instances }}" 
      become: yes 
      yum: 
       name: 
        - httpd 
       state: present 
       
    - name: "Creating index.html" 
      delegate_to: "{{ item.private_ip }}"  
      with_items: "{{ ec2.instances }}" 
      become: yes 
      copy:
        content: "<h1>It works !</h1>"
        dest: /var/www/html/index.html
        remote_src: yes

    - name: "Restart Apache" 
      delegate_to: "{{ item.private_ip }}"  
      with_items: "{{ ec2.instances }}" 
      become: yes 
      service: 
        name: httpd 
        state: restarted 
        enabled: yes
        
    
